RakNet implementation
HerryYT/jukebox pull request #1
Opened 2019-12-16 14:56 UTC by enricoangelon

2019-12-16 18:58 UTC, lucat1 requested changes

2019-12-16 18:58 UTC, lucat1 commented on packages/raknet/src/packets/unconnected-pong.ts
> +export class UnconnectedPong extends Packet {
*Ping (idk)

Seguendo il commento sopra devi anche implementare `IPacket`
```suggestion
export class UnconnectedPong extends Packet implements IPacket {
```

2019-12-16 18:58 UTC, lucat1 commented on packages/raknet/src/packets/packet.ts
> +  public stream: BinaryStream
`protected` anzi che `private`. Metti un metodo `getBuffer()` che ritorna `this.stream.getBuffer()` dato che e' il suo unico utilizzo ed e' pericoloso esporlo all'esterno della classe

2019-12-16 18:58 UTC, lucat1 commented on packages/raknet/src/socket.ts
> +            packet.stream.getBuffer(),
Usa il metodo che devi creare come ti ho scritto sopra

2019-12-16 18:58 UTC, lucat1 commented on packages/raknet/src/socket.ts
>        switch (pid) {
Non si puo' mantenere una cosa simile per sempre. Crea un object costante, al quale ogni key equivale una funzione(ogni funzione in un file) che gestisce il suo evento.

2019-12-16 18:58 UTC, lucat1 commented on packages/raknet/src/packets/unconnected-pong.ts
> +    let serverName = 'MCPE;Jukebox server;105;1.14;0;9000'
1. Custom tramite configurazione
2. Commenta tutto, non si capisce cosa significano quelle `,` e quei numeri

2019-12-16 18:58 UTC, lucat1 commented on packages/raknet/src/packets/packet.ts
> +  public encode() {}
Usa una interface per dei metodi simili. Non solo e' inutile definire un metodo vuoto, ma con una interface costringi anche le altre classi che estendono packet a implementare i due metodi.

```typescript
interface IPacket {
  decode(): void
  encode(): void
}
```

Poi rimuovi quei metodi dalla classe `Packet` e ogni classe che estende `Packet`(es:`UnconnectedPong`) deve anche implementare `IPacket`

2019-12-19 17:32 UTC, lucat1 commented on packages/raknet/src/packets/packet.ts
> +export class Packet implements IPacket {
l'interfaccia IPacket deve essere implementata da tutti gli altri pacchetti, non dalla classe base `Packet`. Rimuovila da qua' a rimuovi quei metodi `decode` e `encode` sotto. Ti ho fatto usare l'interfaccia proprio per non doverli implementare nella classe di base `Packet`

2019-12-21 17:42 UTC, enricoangelon commented
![Screenshot (141)](https://user-images.githubusercontent.com/34418030/71311691-ac369380-2421-11ea-8e14-52a800e5e491.png)

2020-01-10 20:19 UTC, lucat1 requested changes
Fixa.

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/packets/connection-request-accepted.ts
> +import { Packet, IPacket } from '../protocol/packet'
tutti i public/private in questa classe

2020-01-10 20:19 UTC, lucat1 commented on packages/binarystream/src/binary-stream.ts
> +  putInt(v: number) {
public/private

2020-01-10 20:19 UTC, lucat1 commented on packages/binarystream/src/binary-stream.ts
> +  public append(buf: any) {
`buf: string | Buffer | []number`

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/packets/connection-request-accepted.ts
> +  constructor(
Inutile se non scrivi niente di custom nel constructor. Rimuovilo

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/packets/connection-request-accepted.ts
> +        typeof this.systemAddresses[i] !== 'undefined'
Se fai questo check prendilo dalla configurazione, non definirlo sopra in modo statico.

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/packets/open-connection-reply-1.ts
> +  public serverSecurity: number
` public serverSecurity: number = 0`

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/packets/open-connection-reply-1.ts
> +  public mtuSize: number
`public mtuSize: number = this.inputStream.getShort()`

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/packets/open-connection-reply-1.ts
> +  constructor(
Rimuovi il constructor e' inutile

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/packets/open-connection-reply-1.ts
> +  encode() {
public!!

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/packets/open-connection-reply-2.ts
> +  constructor(
Vedi tutti i commenti in `open-connection-reply-1.ts` stessi errori.

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/packets/unconnected-pong.ts
> +  encode() {
public

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/packets/unconnected-pong.ts
> +    this.pingID = this.inputStream.getLong()
Puoi farlo sopra a riga `11`. Inutile.

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/protocol/datagram.ts
> +  decode() {
PUBLIC

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/protocol/datagram.ts
> +  encode() {
P.U.B.L.I.C

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/protocol/datagram.ts
> +    //forEach is slow... waiting for Luca: this.packets.forEach(packet => this.stream.append(packet))
Si e' lento. Usa un for loop come stai facendo. Rimuovi sto commento

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/protocol/encapsulated.ts
> +  //TODO: fix arg and class variables
La PR non sara' accettata finche' non finisci tutti i TODO

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/protocol/encapsulated.ts
> +  static fromBinary(stream: BinaryStream) {
private? public?!

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/protocol/encapsulated.ts
> +  toBinary() {
private? public?!

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/protocol/reliability.ts
> +export const Reliability = {
Trasforma sto schifo in un enum.

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/session.ts
> +  static create(
private? public?!

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/session.ts
> +  static remove(session: RakNetSession, reason?: string) {
private? public?!

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/session.ts
> +  static get(address: string) {
private? public?!

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/session.ts
> +    //TODO: method to retrive session
Se non e' usato da nessuna parte, ne implementato rimuovilo.

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/session.ts
> +      //forEach is slow... does luca approve? packet.packets.forEach(pk => this.handleEncapsulatedPacket(rinfo, pk))
Leva il commento, si tiene il for loop.

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/session.ts
> +//;(async function() {
Leva sti commenti

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/session.ts
> +  getStartTime() {
private? public?!

Rimuovi se non e' usato da nessuna parte.

2020-01-10 20:19 UTC, lucat1 commented on packages/raknet/src/socket.ts
> +  //private static packetsList: Map<number, Object>
rimuovi

2020-01-15 15:48 UTC, enricoangelon commented on packages/raknet/src/session.ts
> +    //TODO: method to retrive session
Ora tolgo anche il metodo remove() dato che per tenere le sessioni sto usando una map con accesso statico e pubblico

2020-01-26 19:01 UTC, lucat1 requested changes
Oltre a tutto quesit devi anche rimuovere il file `package-lock.json` nel pacchetto di jukebox.
Hai installato il pacchetto `jwt-decode` dentro a `jukebox` mentre lo usi dentro a `@jukebox/network` quindi levalo e installalo dentro al pacchetto giusto.

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/package.json
> +    "@types/jwt-decode": "^2.2.1"
Leva il ^. Usa sempre `yarn add -E` (`-E` sta per `exact` che non ti mette questo simbolo). In semantic versioning `^2.2.0` significa "tutte le versioni che iniziano con `2.2` dalla `2.2.0` in su. Quindi in un futuro un utente che installa il pacchetto potrebbe usare la versione `2.2.1` dove c'e' un cambiamento che rompre il tuo codice(anche se nelle minor version non dovrebbe accadere, ma non tutti rispettano semver).

Morale della storia leva quel `^` e usa sempre la flag `exact`

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/jukebox.ts
> +import { Socket } from '@jukebox/raknet'
Metti gli import non locali (senza `.`) in cima e separali con una nuova riga dal resto. Quelli non locali provengono da pacchetti esterni. E' piu' ordinato.

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/level/chunk.ts
> +import { BinaryStream } from '@jukebox/binarystream'
Metti gli import non locali (senza `.`) in cima e separali con una nuova riga dal resto. Quelli non locali provengono da pacchetti esterni. E' piu' ordinato.

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/level/chunk.ts
> +    subChunks = new Map(),
:fire: rimuovi `= new Map()` e' inutile, lo definisci gia' sopra a riga 9

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/level/sub-chunk.ts
> +export interface SubChunkInterface {
Rinomina in `ISubChunk` e spostala nel file `i-sub-chunk.ts`

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/network/packets/resource-pack-client-response.ts
> +import { ResourcePackClientResponses } from '../types/resource-packs/resource-pack-client-responses'
Riusciamo a dargli un nome piu' corto e leggibile grazie?

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/network/packets/resource-pack-client-response.ts
> +export class McpeResourcePackClientResponse extends Datagram {
Riusciamo a dargli un nome piu' corto e leggibile grazie?

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/network/packets/resource-packs-info.ts
> +      this.behaviorPackList.push(<ResourcePack>{
`<ResourcePack>` inutile

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/network/protocol/batched.ts
> +    console.log(pid)
leva

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/network/raknet-instancer.ts
> +import { RemoteInfo } from 'dgram'
Metti gli import dei pacchetti in cima

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/network/raknet-instancer.ts
> +  // Any used because Datagram is already used in batched and is cyclic :'(
?!?!

2020-01-26 19:01 UTC, lucat1 commented on packages/jukebox/src/player.ts
>  import { Socket } from '@jukebox/raknet'
Ordina sti dannati importi. In cima quelli che vengono dai pacchetti esterni

2020-01-26 19:16 UTC, lucat1 requested changes

2020-01-26 19:16 UTC, lucat1 commented on packages/jukebox/src/network/packet-handler.ts
> +import { AsyncResource } from 'async_hooks'
Perche' hai importato sto pacchetto e sta classe se non la usi? Pacchetto per lo piu' che non e' nemmeno nelle dependencies

2020-01-27 13:07 UTC, enricoangelon commented on packages/jukebox/src/network/raknet-instancer.ts
> +  // Any used because Datagram is already used in batched and is cyclic :'(
sendDataPacket(packet: Batched | any
any lo ho dovuto mettere perche' Datagram non poteva andare per lib cicliche

2020-01-27 16:45 UTC, lucat1 approved these changes
LGTM👍

2020-01-27 16:45 UTC, merged